import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches

st.set_page_config(page_title="Line Chemistry & Synergy Evaluator", layout="wide")
st.title("5-Player Line Chemistry & Tactical Evaluator")

# Load & Clean Data
def load_data():
    df = pd.read_csv('shots_data.csv')
    
    # Force coordinate numeric conversion & handle string NaNs
    df['x_coord'] = pd.to_numeric(df['x_coord'], errors='coerce')
    df['y_coord'] = pd.to_numeric(df['y_coord'], errors='coerce')
    
    line_cols = ['f1', 'f2', 'f3', 'd1', 'd2']
    for col in line_cols:
        df[col] = df[col].astype(str).str.strip().replace({'': 'None', 'nan': 'None', 'None': 'None'})
        
    return df.dropna(subset=['x_coord', 'y_coord'])

df = load_data()

st.sidebar.header("Select 5-Player Line Unit")

# Player Pools
forwards = ['Brandon Barrett', 'Zac Sirota', 
    'Ivan Bondarenko', 'Parker Bonsignore', 'Graham Burke',
    'Nick Cyprian', 'Sam Dabrowski', 'Chance Gorman', 'Sihong (Steve) Guo',
    'Caleb Lepitre', 'Gehrett Sargis', 'C J Stubbs', 'Nicholas Swain',
    'Ludovik Tardif', 'Amir Valiullin', 'Gavin Yates', 'Ivan Kulgin', 'Tristan Miron',
    'William Mitchell', 'Tyson Kirkby', 'Kyle Stephan', 'Jansen Mac', 'Scott Ramaekers', 'None']

defensemen = ['Jacob Hamilton', 'Martins Leps', 
    'Scott Ramaekers', 'Dan Wieber', 'Jesse Anderson',
    'Marquise Brown', 'Cheechoo Lathlin', 'Daniel Stone', 'Camron Cervone', 'None']

# Player Selectors
f1 = st.sidebar.selectbox("Forward 1 (LW)", forwards, index=0)
f2 = st.sidebar.selectbox("Forward 2 (C)", forwards, index=1)
f3 = st.sidebar.selectbox("Forward 3 (RW)", forwards, index=2)

st.sidebar.markdown("---")
d1 = st.sidebar.selectbox("Defenseman 1 (LD)", defensemen, index=0)
d2 = st.sidebar.selectbox("Defenseman 2 (RD)", defensemen, index=1)

selected_line_forwards = [f1, f2, f3]
selected_line_defense = [d1, d2]

# 1. Offensive Shots Generated by Black Bears
offense_df = df[
    (df['team_shooting'] == 'Binghamton Black Bears') &
    (df['f1'].isin(selected_line_forwards)) &
    (df['f2'].isin(selected_line_forwards)) &
    (df['f3'].isin(selected_line_forwards))
]

# 2. Defensive Shots Allowed (When opponent shoots while this Black Bears unit is defending)
defense_df = df[
    (df['team_shooting'] == 'Opponent') &
    (df['f1'].isin(selected_line_forwards)) &
    (df['f2'].isin(selected_line_forwards))
]

# Key Line Calculations
shots_for = len(offense_df)
goals_for = offense_df['is_goal'].sum()
shooting_pct = (goals_for / max(1, shots_for)) * 100

shots_against = len(defense_df)
goals_against = defense_df['is_goal'].sum()

# High Danger Chances (Shots taken within the slot: X >= 65 and Y between -15 and 15)
high_danger_for = len(offense_df[(offense_df['x_coord'] >= 65) & (offense_df['y_coord'].between(-15, 15))])
high_danger_pct = (high_danger_for / max(1, shots_for)) * 100

# Corsi / Shot Share Calculation
total_shots = shots_for + shots_against
shot_share_pct = (shots_for / max(1, total_shots)) * 100

# Top Header
st.subheader(f"Selected Line: **{f1} - {f2} - {f3}** | **{d1} - {d2}**")

# Display Metrics
m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("Shot Share (Corsi)", f"{shot_share_pct:.1f}%", help="% of total shots controlled by this line")
m2.metric("Goals Created", f"{goals_for}", f"{shooting_pct:.1f}% Shooting")
m3.metric("Goals Allowed", f"{goals_against}", f"-{shots_against} Shots Conceded", delta_color="inverse")
m4.metric("High Danger %", f"{high_danger_pct:.1f}%", f"{high_danger_for} Slot Chances")
m5.metric("Line Rating", "A-" if shot_share_pct > 55 else "B", "Tactical Fit")

st.markdown("---")

# Draw Rink Visualization
fig, ax = plt.subplots(figsize=(10, 5))
ax.set_xlim(-100, 100)
ax.set_ylim(-42.5, 42.5)
ax.set_facecolor('#f8f9fa')

# Rink Outlines
rink_border = patches.Rectangle((-100, -42.5), 200, 85, linewidth=2, edgecolor='black', facecolor='none')
ax.add_patch(rink_border)
ax.plot([0, 0], [-42.5, 42.5], color='red', linewidth=2)
ax.plot([-25, -25], [-42.5, 42.5], color='blue', linewidth=2)
ax.plot([25, 25], [-42.5, 42.5], color='blue', linewidth=2)
ax.plot([-89, -89], [-42.5, 42.5], color='red', linewidth=1)
ax.plot([89, 89], [-42.5, 42.5], color='red', linewidth=1)

# Single scatter calls to avoid multi-plotting
ax.scatter(offense_df['x_coord'], offense_df['y_coord'], c='green', alpha=0.7, label='Shots For (Offense)', s=60)
ax.scatter(defense_df['x_coord'], defense_df['y_coord'], c='red', alpha=0.6, label='Shots Allowed (Defense)', s=60)

ax.grid(True, linestyle='--', alpha=0.5)
ax.set_title("Line Shot Generation vs. Shots Allowed Map", fontsize=12, fontweight='bold')
ax.legend(loc='upper left')

st.pyplot(fig)

# Tactical Recommendations
if shot_share_pct >= 55:
    st.success("💡 **Coach Recommendation:** **Top Offensive Line**. Excellent puck possession and high-danger chance generation.")
elif shots_against <= 10:
    st.info("💡 **Coach Recommendation:** **Shutdown Line**. Suppresses opponent shot generation effectively.")
else:
    st.warning("💡 **Coach Recommendation:** **Depth / Rotation Line**. High shot volatility allowed in defensive zone.")